language: go

notifications:
  email: false

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: s3
  access_key_id: AKIAIIFQT3CDHC7J3ZHA
  secret_access_key:
    secure: "N83gxqB1+AhrK/KSjTQe/y0EzI9z2SnwwfujJP0fb746p940EeZ7FzNnrZkzoKmhqm8A8eoDp1YfYSqC+4t5aN7uSh+cTKQ5IAcow+osBrgsh6KxNLiLpXrAID4xs9lygF1Zrd6XhsleM/WCPBA4jcOQqIDaBPAfBTfv2OP+BfFXJbHfHoVRgLCudgp89WA3Ur86JYLJQPwhvHJ4hsD9MmNSU83iUzdyc3n4Zu1+iWfc7o02RYOQ46S756LJqjqnDCtojUnqBPYyvqzi8BBqU/33+gckNnrVmrsITs6S9mTiRYFNDoUZy8EbgHbz4gqSgAyHFOD9ljcU19KAUCENR6QQwkdEzKyK0X5kadCoeFfawBWNI1FnjVtXuKGF50tUR+ZrdBWPUXilzs4E14HnejLVYlk8MDlOZrTkI8yhUbNezFIxBQ6I+MjsezvY1k+jFBPNuCoO5sa/z4VQKThViZbuAVqm0fc9N8VUTlEeuTvGJtlofIW3Z87MFGk8oehs9dR7ANNN75vJAHULRR+MbiS5cBNjHyUCzkX3FCx4qL+OU0bhT1OaTQTLYW3wJlsKG1ka16DmtXpyPZTS99qm/RY7CMPEATMC8lCBBbfQEHpiCCn4VIaAorv1YtNuzTyLPX8janYGnxHsJ4L814Un6CKC7vdQkBzTt9yGoJ3hiQk="
  bucket: "swhalley.ca"
  skip_cleanup: true
  region: "ca-central-1"
  local_dir: "public"