language: go

notifications:
  email: false

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: s3
  access_key_id: $ACCESS_KEY
  secret_access_key: $SECRET_KEY
  bucket: "swhalley.ca"
  skip_cleanup: true
  region: "ca-central-1"
  local_dir: "public"