language: go
notifications:
  email: false
install:
- go get github.com/spf13/hugo
script:
- hugo
deploy:
  provider: s3
  access_key_id: AKIAIIFQT3CDHC7J3ZHA
  bucket: swhalley.ca
  skip_cleanup: true
  region: ca-central-1
  local_dir: public
  secure: Abc5BmeNZ4Oxh5YzQHGixWwPTgtpVTSD/rrkS5PZ6gqx6er/oSpSwEy3G/wDq7rfDr4k6CO8baNTfJiMpt1kTySCs6rq3/6Hkyk1PS5CW3TCXbvyTgFao1kxHWMtUF7jqdEKbYktCuTMvvDbu2Ch1ocwSkGjaCGrlOfmPU6f8fp+S9KwstRTmy+5qyLwnI0aFEE5otslUdTeDwK3oGQeJpDPDUrFLGLj3bzlR0UH8jVFfeeBDQ+C7O63kTUjKGMDrgNWg22Ep7Z3CDzCbVq2UJT74UireFTTQTlTpHnzALY3cTz1sIj9uQe5ccGwmnnCMMdYkErwqtT/m8Oic6lzSApOWfhcYIniBvwAn9EX8vRoAlCNXQECA7UixiQ6rnfShuTr5XIhaL+eTxqql5C6fSx0+UM53HdHPr0E/oisyRPtZtJw+h9SsWWPbZK5D1DhFKKPqyII86Wb0nqqbqkw6GxyOcFOeJK5almW51snnulMZmL7NZFljArU4blqrmlNBVZwJfsGle+Rn3emifXOOCzW4c9bbhl3UNxXf1vj2ElkZXWgEVWcw7DD462JcsgQe+BzwtepqEibeCCLSrdVBiB1XZsD1VoZvqenseNneAieoRJSVj1p8ZXdPUJf1bLnoVQryCOYbdVYRuuN2+Ymk3KGheSuvrshScRjCFhWyKM=
