language: go
notifications:
  email: false

#env:
#  global:
#    secure: jrzb6Z+jTitbmalVZU+BhuMi5pydPxMVdZdWr4aPmfSu+SYGB0o1FN7wyU2mtBJiQEdQMQwx7YiLsXlV4eTMG4dwdCT7Vs4as4Tyq8e1TH8wYrkkp2GVO8ok7lkVFchyZHhTF3gfFmXFycYRs9nKrYMzNcPkJv/1QUo1q0gr6NPZ8XkKk2nT2lpVQeYNl8Ajf6+owEbAVV1+vI26BfDHxg9LfX6U4M4mMPXt1fI2q4eIZIMC2iyftU9HmBYxlTgW2KWYf0e90hHHji0GI7rwiHemz1v3/Mu+jiqDGXnXe3dE9fKXT04DE7Y8wUYlEmA6+giKNZKSGwt0LmlGYBGF/CtsjoiL7lGnVHW8nOyqZvuFegCI4y1G9yW1SYZ4dx75IAwsQSF/zko9yZQ/LFwl/j6cNoTnR83xmQ38ad4I/SbUS+fOlSHw867H3tmxq2o66byAayuVat10jtFPq0aERXdaYK1nLsQ4rTeYscbWQqNMJNSlO3MBNIIjyRuHLVYt2cviyamCP8N9TRfWfckO8apIJh5zdMMh8w+bNcMS/6L52Fg8GUDmsLn9Y3u1CMCqdJTpGxoMtJBQHf9vzZu1TwqK6ZUYzarHndyhJAxB7CBqfmfmedcfLAegwVlPCzdpwvzrymk6r7RHNrLCJhGymcZYUG27xIttHv426paSkTw=

  
install:
  - go get github.com/spf13/hugo

script:
  - pwd
  - find . -name \*.* -print
  - hugo 

#deploy:
#  provider: s3
#  access_key_id: "AKIAIC5TNWBXKHZL5LXA"
#  bucket: "swhalley.ca"
#  skip_cleanup: true
#  region: "ca-central-1"
#  local_dir: public