language: go
notifications:
  email: false

install:
  - go get github.com/spf13/hugo

script:
  - hugo

deploy:
  provider: s3
  access_key_id: AKIAIIFQT3CDHC7J3ZHA
  bucket: swhalley.ca
  skip_cleanup: true
  region: ca-central-1
  local_dir: public
  secret_access_key:
    secure: YyNWlCoH/gQxYcB8VDlwDW4LXLyJwIYZf7JI9wf7l9q+GGDowDESMgKntN9R+T3Re9tjvJ5qewJLdsYuQlT9eMvBDBp585l2qNB14a833Lv4k2SosEbu6+lW4Q/XbUfrazohPGOdag20BA1hktzCsakeIS21p1ZAaenKUxHV8vIGXL+CkbFmLj4oueLs07103UmjTFXtg5S24y9P45O5TzM0AsRdGNrU6bOMdUftFp6M6BEVr6Gb1cZ61034VFzTVh7GLu/lDSqf3ZzZb63Xc3IbWH7y5J2vkZQQSDlCMm2WtDYX0ucnULbSzX2Fbf3cVn9pgZFDGWYivrmsP5NO28HxxCpNZjR7e35Y8le4sm9yk8ox8iAfF/HQJQI/77kR/YNcLfRtB5MS3X3ed7/TwpkFUjHJsxGUm2Pqol8bXuwFpk2sbZNfpo/ZXSwfKLluIZRNwm2BLKmdZeZErOglgnIgVHBhS6vKrFjmrGBmfqzCYLljFeKuGZY7+OYwABDHq/Is6mv4cZdvUtnK/ggWoBYpA2jdhtXFRpCrwPiw926JHS+3o8HewATeKogIOschlv6nJ3pdfU2icoMgCEGNRGuTVZPOGOYoWnbl6/IaN+pMdUw345A00Z91Nv7Z8adJaX8dNq23lKZzAQ+JKMCzwqpz1MZl0Jxk8NDcirPYbQw=
