baseURL = "http://example.org/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "freelancer"

[params]
    [params.navigation]
        brand = "My Thoughts"
    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Sean Whalley"
        subtitle = "Jedi Knight Developer"
