_baseURL = "http://swhalley.ca/"
baseURL = "http://swhalley.ca.s3-website.ca-central-1.amazonaws.com/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "freelancer"

[params]
    [params.navigation]
        brand = "My Thoughts"
    [params.header]
        # Copy your own image into './static/img/'' if you wish
        image = "profile.png"
        name = "Sean Whalley"
        subtitle = "Jedi Knight Developer"

[params.footer]
        copyright = "Powered by [Hugo](//gohugo.io)."

