baseURL = "http://swhalley.ca/"
languageCode = "en-us"
theme = "blog-style"

title = "Sean's Thoughts"


[params]
subtitle = "Development made \"easy\""
author = "Sean Whalley"

[communication]
email = "swhalley at gmail.com"
github = "swhalley"
twitter = "seanWhalley21"

[[menu.main]]
  name = "Home"
  weight = 1
  url = "/"

[[menu.main]]
  name = "Work"
  weight = 3
  url = "https://github.com/swhalley"

[[menu.main]]
  name = "About"
  weight = 2
  url = "/about"